name: Script Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      SCRIPTS_PAT_TOKEN: ${{ secrets.SCRIPTS_PAT_TOKEN }}
      org_name: "gitstua-labs"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # W sign in with a custom pat token to run scripts. 
      # Note you cannot use an ENV named GH_TOKEN as this gives an error
      - name: Run get-commits-count.sh
        run: |
          echo $SCRIPTS_PAT_TOKEN | gh auth login --with-token
          chmod +x ./get-commits-count.sh
          ./get-commits-count.sh      