name: Script Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.SCRIPTS_PAT_TOKEN }}
      org_name: "gitstua-labs"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # run ./get-commits-count.sh
      - name: Run get-commits-count.sh
        run: |
          # login to github
          gh auth login
          gh auth status
          chmod +x ./get-commits-count.sh
          ./get-commits-count.sh      